<template>
 <view class="movement-library">
  <view class="section-heading"><view><text class="eyebrow">MOVEMENT / 01—10</text><text class="page-title">{{et('library')}}</text><text class="muted small">{{et('subtitle')}}</text></view><view class="movement-count"><AppIcon name="grid"/><text>10 {{et('count')}}</text></view></view>
  <view class="movement-library-layout"><view class="movement-detail panel"><ExercisePlayer :exercise="selected"/><view class="movement-meta"><text class="card-title">{{exerciseName(selected)}}</text><text class="muted small">{{exerciseMeta(selected)}}</text></view><text class="movement-credit">{{et('source')}}</text><button role="button" tabindex="0" class="text-button movement-source" @click="copyExerciseSource">{{et('copySource')}} <AppIcon name="arrow"/></button></view>
   <view class="movement-catalog"><view class="movement-filters"><button class="movement-filter" v-for="group in groups" :key="group" role="button" tabindex="0" :class="{selected:filter===group}" @click="filter=group">{{et(group)}}</button></view><view class="movement-grid"><button v-for="exercise in filtered" :key="exercise.slug" role="button" tabindex="0" class="movement-card" :class="{selected:selected.slug===exercise.slug}" :aria-label="et('view')+' '+exerciseName(exercise)" :aria-pressed="selected.slug===exercise.slug" @click="selected=exercise"><view class="movement-thumb"><ExerciseArt :exercise="exercise"/><view v-if="selected.slug===exercise.slug" class="movement-selected"><AppIcon name="check" tone="white"/></view></view><view class="movement-card-copy"><text class="movement-card-name">{{exerciseName(exercise)}}</text><text class="movement-card-meta">{{exerciseMeta(exercise)}}</text></view></button></view></view>
  </view>
 </view>
</template>
<script setup lang="ts">
import {ref,computed} from 'vue';import AppIcon from './AppIcon.vue';import ExerciseArt from './ExerciseArt.vue';import ExercisePlayer from './ExercisePlayer.vue';
import {exercises,exerciseName,exerciseMeta,et,copyExerciseSource} from '../lib/exercises';
const groups=['all','strength','mobility','cardio'] as const;
const filter=ref<typeof groups[number]>('all'),selected=ref(exercises[3]);
const filtered=computed(()=>exercises.filter(e=>filter.value==='all'||(filter.value==='strength'?e.activity==='strength':filter.value==='mobility'?e.activity==='yoga':['run','walk','cycle'].includes(e.activity))));
</script>
<style scoped>
.section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px}.eyebrow{display:block;color:#7d8d71;font-size:10px;letter-spacing:1.5px;margin-bottom:10px}.page-title{display:block;color:#203e2d;font-weight:650;line-height:1.4}.muted{display:block;color:#839077;line-height:1.7}.small{font-size:11px}.panel{background:#fff;border:1px solid #e0e7d8;border-radius:18px}.card-title{display:block;font-weight:600;color:#294831;line-height:1.5}.text-button{padding:4px 0;background:transparent;color:#5c7951;line-height:1.8}.movement-card{width:100%;margin:0}.movement-filter{margin:0}.movement-card::after,.movement-source::after{border:0}
.movement-library{margin:30px 0 38px}.movement-library .page-title{font-size:26px;margin-bottom:8px}.movement-count{display:flex;align-items:center;gap:8px;color:#819076;font-size:11px;white-space:nowrap}.movement-count .icon{font-size:18px}.movement-library-layout{display:grid;grid-template-columns:minmax(270px,.9fr) minmax(0,1.5fr);gap:24px;align-items:start}.movement-detail{padding:18px;min-width:0}.movement-meta{margin-top:22px}.movement-meta .card-title{font-size:20px;margin-bottom:5px}.movement-credit{display:block;font-size:10px;line-height:1.8;color:#86927b;margin-top:22px}.movement-source{display:flex;align-items:center;gap:5px;font-size:10px;white-space:normal;text-align:left}.movement-source .icon{font-size:12px}.movement-filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:16px}.movement-filter{padding:7px 13px;background:#fff;border:1px solid #e0e7d9;font-size:11px;line-height:20px;border-radius:8px;color:#76876e}.movement-filter.selected{color:#fff;background:#315b46;border-color:#315b46}.movement-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.movement-card{padding:0;text-align:left;background:#fff;border:1px solid #e1e7dc;border-radius:12px;overflow:hidden;line-height:1.4;min-width:0}.movement-card.selected{border-color:#56794d;box-shadow:0 0 0 1px #56794d}.movement-thumb{height:115px;padding:8px;background:#345545;position:relative}.movement-card:nth-child(3n+2) .movement-thumb{background:#4c6253}.movement-card:nth-child(3n) .movement-thumb{background:#536252}.movement-selected{position:absolute;right:7px;top:7px;width:20px;height:20px;background:#789963;border-radius:50%;display:flex;align-items:center;justify-content:center}.movement-selected .icon{font-size:13px}.movement-card-copy{padding:11px}.movement-card-name{display:block;font-size:12px;font-weight:600;color:#34503b;overflow-wrap:anywhere}.movement-card-meta{display:block;font-size:9px;color:#8b967e;line-height:1.6;margin-top:5px;overflow-wrap:anywhere}
@media(max-width:1180px){.movement-library-layout{grid-template-columns:minmax(230px,.9fr) minmax(0,1.2fr)}.movement-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){.movement-library-layout{grid-template-columns:1fr;gap:20px}.movement-library{margin-top:22px}.movement-count{display:none}.movement-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.movement-thumb{height:140px}.movement-detail{padding:15px}.movement-card-name{font-size:13px}.movement-card-meta{font-size:10px}.movement-library .page-title{font-size:24px}}
</style>
