<template>
 <view class="app-shell">
  <view class="sidebar">
   <view class="brand"><view class="brand-mark"><AppIcon name="brand" tone="lime"/></view><view><text class="brand-name">FitStreak</text><text class="brand-tag">{{t('tagline')}}</text></view></view>
   <view class="nav"><button role="button" tabindex="0" v-for="item in nav" :key="item" class="nav-item" :class="{active:page===item}" @click="navigate(item)"><AppIcon :name="item" :tone="page===item?'forest':'muted'"/><text>{{t(item)}}</text></button></view>
   <view class="sidebar-bottom"><text class="small-overline">ONE DAY STRONGER</text><text class="sidebar-note">{{t('motivator')}}</text><view class="tiny-status"><view class="status-dot"/>{{t(demoMode?'demo':'live')}}</view></view>
  </view>
  <view class="main">
   <view class="topbar"><view class="mobile-brand"><view class="brand-mark"><AppIcon name="brand" tone="lime"/></view><text class="brand-name">FitStreak</text></view><text class="breadcrumb">{{t(page)}}</text><view class="top-actions"><button role="button" tabindex="0" class="language-button" @click="toggleLanguage">{{locale==='zh-CN'?'EN':'中文'}}</button><button role="button" tabindex="0" class="avatar" @click="navigate('profile')">{{(me?.nickname||'F').slice(0,1).toUpperCase()}}</button></view></view>
   <view v-if="!sessionReady && page!=='learn'" class="welcome panel"><text class="eyebrow">FITSTREAK / {{t('tagline')}}</text><text class="hero-title">{{t('welcome')}}</text><text class="muted">{{t('loginHint')}}</text><button role="button" tabindex="0" class="primary" :disabled="busy" :aria-disabled="busy" @click="login">{{t(demoMode?'login':'wechatLogin')}}</button><text v-if="error" class="error-text">{{t(error)}}</text></view>
   <view v-else class="content">
    <view v-if="loading" class="state-panel">{{t('loading')}}</view>
    <view v-if="error" class="error-banner"><text>{{t(error)}}</text><button role="button" tabindex="0" class="small-button" @click="load">{{t('retry')}}</button></view>
    <template v-if="page==='home'">
     <view class="hero"><view class="hero-copy"><text class="eyebrow">{{dateLabel}} · FITSTREAK</text><text class="hero-title">{{t('greeting')}}</text><text class="hero-subtitle">{{t('subtitle')}}</text><button role="button" tabindex="0" class="primary" @click="openPlan()"><AppIcon name="plus" tone="white"/>{{t('newPlan')}}</button></view><view class="hero-movement"><view class="hero-movement-orbit"/><view class="hero-movement-image"><ExerciseArt :exercise="exercises[4]" :frame="2"/></view><view class="hero-movement-note"><text>{{et('hero')}}</text><text>{{exerciseName(exercises[4])}} · 02 / 03</text></view><button role="button" tabindex="0" class="hero-movement-link" @click="openLibrary"><AppIcon name="arrow" tone="white"/><text>{{et('browse')}}</text></button></view></view>
     <view class="metric-grid"><view v-for="m in metrics" :key="m.key" class="metric panel"><view class="metric-heading"><text>{{t(m.key)}}</text><view class="metric-symbol" :class="m.color"><AppIcon :name="m.icon"/></view></view><view class="metric-value">{{m.value}}<text>{{t(m.unit)}}</text></view><text class="muted small">{{t(m.key==='streak'?'dateHint':'week')}}</text></view></view>
     <view class="dashboard-grid"><view class="panel sessions"><view class="section-heading"><view><text class="section-title">{{t('today')}}</text><text class="muted small">{{dateLabel}}</text></view><button role="button" tabindex="0" class="text-button" @click="navigate('plans')">{{t('viewAll')}} →</button></view><view v-if="!todayPlans.length" class="empty"><AppIcon name="plans"/><text>{{t('emptyPlans')}}</text><text class="muted">{{t('emptyHint')}}</text><button role="button" tabindex="0" class="outline" @click="openPlan()">{{t('newPlan')}}</button></view><view v-for="plan in todayPlans" :key="plan.id" class="session-row"><view class="session-art"><ExerciseArt :exercise="referenceFor(plan.activity)"/></view><view class="session-detail"><text class="item-title">{{plan.title}}</text><text class="muted small">{{t(plan.activity)}} · {{plan.target_minutes}} {{t('min')}}</text></view><button role="button" tabindex="0" class="check-button" :class="{completed:isDone(plan.id)}" :disabled="isDone(plan.id)" :aria-disabled="isDone(plan.id)" @click="openCheckin(plan)">{{t(isDone(plan.id)?'done':'checkIn')}}<text v-if="!isDone(plan.id)"> →</text></button></view></view>
      <view class="panel goal-card"><view class="section-heading"><text class="section-title">{{t('goal')}}</text><AppIcon name="arrow"/></view><view class="goal-ring" :style="{background:goalGradient}"><text class="goal-number">{{activeThisWeek}}<text>/ {{me?.weekly_goal||4}}</text></text><text class="muted small">{{t('days')}}</text></view><text class="muted small">{{t('goalHint')}}</text><view class="goal-days"><view v-for="(d,i) in weekLabels" :key="i" :class="{marked:weekActive(i)}">{{d}}</view></view></view></view>
     <view class="panel trend"><view class="section-heading"><view><text class="section-title">{{t('progress')}}</text><text class="muted small">{{t('progressHint')}}</text></view><text class="pill">{{t('week')}}</text></view><view class="chart"><view v-for="day in stats7.series" :key="day.date" class="chart-col"><text class="bar-value">{{day.minutes}}</text><view class="bar" :style="{height:barHeight(day.minutes,stats7.series)+'px'}"/><text class="chart-label">{{formatDate(day.date,true)}}</text></view></view></view>
    </template>
    <template v-if="page==='plans'"><view class="page-heading"><view><text class="eyebrow">YOUR RHYTHM</text><text class="page-title">{{t('plans')}}</text><text class="muted">{{t('emptyHint')}}</text></view><button role="button" tabindex="0" class="primary" @click="openPlan()"><AppIcon name="plus" tone="white"/> {{t('newPlan')}}</button></view><view v-if="!plans.length" class="empty panel">{{t('emptyPlans')}}</view><view class="plan-grid"><view v-for="plan in plans" :key="plan.id" class="panel plan-card"><view class="plan-top"><view class="activity-icon" :class="plan.activity"><AppIcon :name="plan.activity"/></view><text class="pill">{{t(plan.activity)}}</text></view><view class="plan-art"><ExerciseArt :exercise="referenceFor(plan.activity)"/><text class="plan-art-label">{{et('reference')}} · {{exerciseName(referenceFor(plan.activity))}}</text></view><text class="card-title">{{plan.title}}</text><text class="plan-duration">{{plan.target_minutes}} <text>{{t('min')}}</text></text><view class="week-pills"><view v-for="(label,i) in weekLabels" :key="i" :class="{selected:plan.weekdays.includes(i+1)}">{{label}}</view></view><text class="muted small">{{formatDate(plan.start_date)}} — {{plan.end_date?formatDate(plan.end_date):t('noEnd')}}</text><view class="plan-actions"><button role="button" tabindex="0" class="text-button" @click="openPlan(plan)">{{t('edit')}}</button><button role="button" tabindex="0" class="text-button muted" @click="archiveTarget=plan">{{t('archive')}}</button><button role="button" tabindex="0" class="check-button" :disabled="isDone(plan.id)||!scheduled(plan)" :aria-disabled="isDone(plan.id)||!scheduled(plan)" @click="openCheckin(plan)">{{t(isDone(plan.id)?'done':scheduled(plan)?'checkIn':'rest')}}</button></view></view></view></template>
    <template v-if="page==='stats'"><view class="page-heading"><view><text class="eyebrow">SMALL STEPS. REAL PROGRESS.</text><text class="page-title">{{t('stats')}}</text></view><view class="segmented"><button role="button" tabindex="0" :class="{selected:range===7}" @click="changeRange(7)">{{t('week')}}</button><button role="button" tabindex="0" :class="{selected:range===30}" @click="changeRange(30)">{{t('month')}}</button></view></view><view class="metric-grid"><view v-for="m in [{key:'minutes',value:statsRange.minutes},{key:'checkins',value:statsRange.checkins},{key:'days',value:statsRange.active_days}]" :key="m.key" class="panel metric"><text class="muted">{{t(m.key)}}</text><text class="metric-value">{{m.value}}</text></view></view><view class="panel trend"><text class="section-title">{{t('daily')}}</text><scroll-view scroll-x class="chart-scroll"><view class="chart" :class="{'chart-long':range===30}"><view v-for="day in statsRange.series" :key="day.date" class="chart-col"><text class="bar-value">{{day.minutes}}</text><view class="bar" :style="{height:barHeight(day.minutes,statsRange.series)+'px'}"/><text class="chart-label">{{formatDate(day.date,true)}}</text></view></view></scroll-view></view><view class="panel history"><view class="section-heading"><text class="section-title">{{t('history')}}</text><text class="muted small">{{t('last30')}}</text></view><view v-if="!history.length" class="empty">{{t('emptyHistory')}}</view><view v-for="row in history" :key="row.id" class="session-row"><view class="activity-icon" :class="row.activity"><AppIcon :name="row.activity"/></view><view class="session-detail"><text class="item-title">{{row.plan_title}}</text><text class="muted small">{{formatDate(row.local_date)}}<text v-if="row.note"> · {{row.note}}</text></text></view><text class="record-minutes">{{row.duration_minutes}} {{t('min')}}</text></view></view></template>
    <template v-if="page==='learn'"><view v-if="article" class="article-detail panel"><button role="button" tabindex="0" class="text-button" @click="article=null">← {{t('back')}}</button><text class="eyebrow">{{t(article.category)}} · {{article.reading_minutes}} {{t('reading')}}</text><text class="page-title">{{article.title}}</text><text class="article-summary">{{article.summary}}</text><text class="article-body">{{article.body}}</text></view><template v-else><view class="page-heading"><view><text class="eyebrow">THE EVERYDAY GUIDE</text><text class="page-title">{{t('knowledgeTitle')}}</text><text class="muted">{{t('knowledgeSubtitle')}}</text></view></view><view class="learn-tabs"><button role="button" tabindex="0" :class="{selected:learnSection==='articles'}" @click="learnSection='articles'"><AppIcon name="learn"/>{{et('articles')}}</button><button role="button" tabindex="0" :class="{selected:learnSection==='movements'}" @click="learnSection='movements'"><AppIcon name="strength"/>{{et('library')}}</button></view><ExerciseLibrary v-if="learnSection==='movements'"/><template v-else><view class="filters"><button role="button" tabindex="0" v-for="c in ['all','habits','training','recovery']" :key="c" :class="{selected:category===c}" @click="category=c">{{t(c)}}</button></view><view class="article-grid"><view v-for="(a,i) in filteredArticles" :key="a.id" class="article-card panel" @click="readArticle(a.id)"><view class="article-art article-movement-art"><view class="article-movement-copy"><text class="art-word">{{['MOVE.','BEGIN.','REST.'][i%3]}}</text><text>{{t(a.category)}}</text></view><view class="article-movement-image"><ExerciseArt :exercise="a.category==='recovery'?exercises[8]:a.category==='training'?exercises[3]:exercises[4]" :frame="2"/></view></view><view class="article-copy"><text class="eyebrow">{{t(a.category)}} · {{a.reading_minutes}} {{t('reading')}}</text><text class="card-title">{{a.title}}</text><text class="muted">{{a.summary}}</text><button role="button" tabindex="0" class="text-button read-link" @click.stop="readArticle(a.id)">{{t('viewAll')}} ↗</button></view></view></view><view v-if="!filteredArticles.length" class="empty">{{t('noArticles')}}</view></template></template></template>
    <template v-if="page==='profile'"><view class="page-heading"><view><text class="eyebrow">YOUR SPACE</text><text class="page-title">{{t('profile')}}</text></view></view><view class="profile-layout"><view class="panel profile-card"><view class="profile-avatar">{{(me?.nickname||'F').slice(0,1).toUpperCase()}}</view><text class="card-title">{{me?.nickname}}</text><text class="muted">{{t('profileHint')}}</text><text class="pill">{{t(demoMode?'demo':'live')}}</text></view><view class="panel preferences"><text class="section-title">{{t('settings')}}</text><view class="field"><text>{{t('nickname')}}</text><input v-model="profileForm.nickname" maxlength="40" :placeholder="t('nickname')"/></view><view class="field"><text>{{t('weeklyGoal')}}</text><input v-model="profileForm.weekly_goal" type="number" :placeholder="t('weeklyGoal')"/></view><view class="field"><text>{{t('language')}}</text><view class="segmented"><button role="button" tabindex="0" :class="{selected:locale==='zh-CN'}" @click="selectLanguage('zh-CN')">简体中文</button><button role="button" tabindex="0" :class="{selected:locale==='en'}" @click="selectLanguage('en')">English</button></view></view><text class="muted small">{{t('dateHint')}}</text><button role="button" tabindex="0" class="primary" :disabled="busy" :aria-disabled="busy" @click="saveProfile">{{t('save')}}</button><button role="button" tabindex="0" class="text-button logout" @click="logout">{{t('logout')}}</button></view></view></template>
    <view class="visual-attribution"><button role="button" tabindex="0" @click="copyExerciseSource">{{et('source')}}</button></view><view class="footer"><text>FitStreak</text><text>{{t('tagline')}} · {{t(demoMode?'demo':'live')}}</text></view>
   </view>
  </view>
  <view class="mobile-nav"><button role="button" tabindex="0" v-for="item in nav" :key="item" :class="{active:page===item}" @click="navigate(item)"><AppIcon :name="item" :tone="page===item?'forest':'muted'"/><text>{{t(item)}}</text></button></view>
  <view v-if="modal" class="overlay" @click="closeModal"><view class="dialog" @click.stop><view class="section-heading"><text class="section-title">{{t(modal==='plan'?(editId?'edit':'newPlan'):'checkTitle')}}</text><button role="button" tabindex="0" class="close" :aria-label="t('close')" @click="closeModal"><AppIcon name="close"/></button></view><scroll-view scroll-y class="dialog-body"><template v-if="modal==='plan'"><view class="field"><text>{{t('title')}}</text><input v-model="form.title" maxlength="80" :placeholder="t('title')"/></view><view class="field"><text>{{t('activity')}}</text><view class="activity-picker"><button role="button" tabindex="0" v-for="a in activities" :key="a" :class="{selected:form.activity===a}" @click="form.activity=a"><AppIcon :name="a"/><text>{{t(a)}}</text></button></view></view><ExerciseReference :activity="form.activity"/><view class="field"><text>{{t('duration')}}</text><input v-model="form.target_minutes" type="number" :placeholder="t('duration')"/></view><view class="field"><text>{{t('weekdays')}}</text><view class="week-picker"><button role="button" tabindex="0" v-for="(label,i) in weekLabels" :key="i" :class="{selected:form.weekdays.includes(i+1)}" @click="toggleDay(i+1)">{{label}}</button></view></view><view class="date-fields"><view class="field"><text>{{t('startDate')}}</text><input v-model="form.start_date" placeholder="YYYY-MM-DD" maxlength="10"/></view><view class="field"><text>{{t('endDate')}}</text><input v-model="form.end_date" placeholder="YYYY-MM-DD" maxlength="10"/></view></view></template><template v-else><view class="check-summary"><view class="activity-icon"><AppIcon :name="checking?.activity||'run'"/></view><text class="item-title">{{checking?.title}}</text></view><ExerciseReference :activity="checking?.activity||'run'"/><view class="field"><text>{{t('actualDuration')}}</text><input v-model="checkForm.duration_minutes" type="number" :placeholder="t('actualDuration')"/></view><view class="field"><text>{{t('note')}}</text><textarea v-model="checkForm.note" maxlength="500" :placeholder="t('notePlaceholder')"/></view><text class="muted small">{{t('dateHint')}}</text></template><text v-if="formError" class="error-text">{{t(formError)}}</text></scroll-view><view class="dialog-actions"><button role="button" tabindex="0" class="outline" :disabled="busy" :aria-disabled="busy" @click="closeModal">{{t('cancel')}}</button><button role="button" tabindex="0" class="primary" :disabled="busy" :aria-disabled="busy" @click="modal==='plan'?savePlan():saveCheckin()">{{t(modal==='plan'?'save':'submit')}}</button></view></view></view>
  <view v-if="archiveTarget" class="overlay"><view class="dialog confirm-dialog"><text class="section-title">{{t('archiveTitle')}}</text><text class="muted">{{t('archiveHint')}}</text><view class="dialog-actions"><button role="button" tabindex="0" class="outline" :disabled="busy" :aria-disabled="busy" @click="archiveTarget=null">{{t('cancel')}}</button><button role="button" tabindex="0" class="primary" :disabled="busy" :aria-disabled="busy" @click="archivePlan">{{t('archive')}}</button></view></view></view>
 </view>
</template>

<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue';
import AppIcon from '../../components/AppIcon.vue';
import ExerciseArt from '../../components/ExerciseArt.vue';
import ExerciseReference from '../../components/ExerciseReference.vue';
import ExerciseLibrary from '../../components/ExerciseLibrary.vue';
import {exercises,referenceFor,exerciseName,et,copyExerciseSource} from '../../lib/exercises';
const learnSection=ref('articles');
function openLibrary(){learnSection.value='movements';navigate('learn');}
import {t,locale,setLocale,formatDate} from '../../lib/i18n';
import {request,signIn,session,demoMode} from '../../lib/api';
const nav=['home','plans','stats','learn','profile'];const activities=['run','strength','yoga','walk','cycle'];
const page=ref('home'),sessionReady=ref(Boolean(session.token)),busy=ref(false),loading=ref(false),error=ref(''),me=ref<any>(null),plans=ref<any[]>([]),history=ref<any[]>([]),articles=ref<any[]>([]),article=ref<any>(null),category=ref('all'),range=ref(7);
const initialStats={today:'',minutes:0,checkins:0,streak:0,active_days:0,series:[] as any[]};const stats7=ref({...initialStats}),statsRange=ref({...initialStats});
const modal=ref(''),editId=ref(''),formError=ref(''),checking=ref<any>(null),archiveTarget=ref<any>(null);
const form=ref<any>({}),checkForm=ref({duration_minutes:'20',note:''}),profileForm=ref({nickname:'',weekly_goal:'4'});
const today=computed(()=>stats7.value.today||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));
const dateLabel=computed(()=>formatDate(today.value));
const weekLabels=computed(()=>['mon','tue','wed','thu','fri','sat','sun'].map(t));
const metrics=computed(()=>[{key:'minutes',value:stats7.value.minutes,unit:'min',icon:'clock',color:'green'},{key:'checkins',value:stats7.value.checkins,unit:'times',icon:'check',color:'orange'},{key:'streak',value:stats7.value.streak,unit:'days',icon:'flame',color:'purple'}]);
function scheduled(p:any){const d=new Date(today.value+'T12:00:00Z').getUTCDay()||7;return p.start_date<=today.value&&(!p.end_date||p.end_date>=today.value)&&p.weekdays.includes(d);}
const todayPlans=computed(()=>plans.value.filter(scheduled));
function isDone(id:string){return history.value.some(h=>h.plan_id===id&&h.local_date===today.value);}
const monday=computed(()=>{const d=new Date(today.value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()||7)-1));return d.toISOString().slice(0,10);});
const goalGradient=computed(()=>`conic-gradient(#8ba879 ${Math.min(100,activeThisWeek.value/(me.value?.weekly_goal||4)*100)}%, #e9efdf 0)`);
const activeThisWeek=computed(()=>new Set(history.value.filter(h=>h.local_date>=monday.value).map(h=>h.local_date)).size);
function weekActive(i:number){const d=new Date(monday.value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);return history.value.some(h=>h.local_date===d.toISOString().slice(0,10));}
const filteredArticles=computed(()=>articles.value.filter(a=>category.value==='all'||a.category===category.value));
function barHeight(n:number,series:any[]){return Math.max(3,n/Math.max(1,...series.map(d=>d.minutes))*110);}
function showError(e:any){error.value=e.message||'error';if(!session.token)sessionReady.value=false;}
async function load(){loading.value=true;error.value='';try{const [u,p,h,s,a]=await Promise.all([request('/api/me'),request('/api/plans'),request('/api/checkins'),request('/api/stats?days=7'),request('/api/articles?locale='+locale.value)]);me.value=u;profileForm.value={nickname:u.nickname,weekly_goal:String(u.weekly_goal)};plans.value=p;history.value=h;stats7.value=s;articles.value=a;statsRange.value=range.value===7?s:await request('/api/stats?days=30');}catch(e){showError(e);}finally{loading.value=false;}}
async function login(){busy.value=true;error.value='';try{me.value=await signIn();sessionReady.value=true;await load();}catch(e){showError(e);}finally{busy.value=false;}}
function logout(){session.token='';sessionReady.value=false;me.value=null;plans.value=[];history.value=[];error.value='';page.value='home';}
function navigate(p:string){page.value=p;article.value=null;if(p==='learn'&&!sessionReady.value)request('/api/articles?locale='+locale.value).then(a=>articles.value=a).catch(showError);}
async function selectLanguage(value:'zh-CN'|'en'){setLocale(value);if(sessionReady.value||page.value==='learn'){try{articles.value=await request('/api/articles?locale='+value);if(article.value)article.value=await request('/api/articles/'+article.value.id+'?locale='+value);}catch(e){showError(e);}}}
function toggleLanguage(){void selectLanguage(locale.value==='en'?'zh-CN':'en');}
async function changeRange(days:number){range.value=days;try{statsRange.value=days===7?stats7.value:await request('/api/stats?days=30');}catch(e){showError(e);}}
function openPlan(p?:any){editId.value=p?.id||'';form.value=p?{title:p.title,activity:p.activity,target_minutes:String(p.target_minutes),weekdays:[...p.weekdays],start_date:p.start_date,end_date:p.end_date||''}:{title:'',activity:'run',target_minutes:'30',weekdays:[1,2,3,4,5,6,7],start_date:today.value,end_date:''};formError.value='';modal.value='plan';}
function closeModal(){if(!busy.value)modal.value='';}
function toggleDay(d:number){form.value.weekdays=form.value.weekdays.includes(d)?form.value.weekdays.filter((x:number)=>x!==d):[...form.value.weekdays,d].sort();}
async function savePlan(){const b={...form.value,title:form.value.title.trim(),target_minutes:Number(form.value.target_minutes),end_date:form.value.end_date||null};if(!b.title||!Number.isInteger(b.target_minutes)||b.target_minutes<1||b.target_minutes>600||!b.weekdays.length||!/^\d{4}-\d{2}-\d{2}$/.test(b.start_date)){formError.value='required';return;}busy.value=true;formError.value='';try{await request('/api/plans'+(editId.value?'/'+editId.value:''),editId.value?'PATCH':'POST',b);modal.value='';await load();}catch(e:any){formError.value=e.message;}finally{busy.value=false;}}
function openCheckin(p:any){checking.value=p;checkForm.value={duration_minutes:String(p.target_minutes),note:''};formError.value='';modal.value='checkin';}
async function saveCheckin(){const n=Number(checkForm.value.duration_minutes);if(!Number.isInteger(n)||n<1||n>600){formError.value='required';return;}busy.value=true;formError.value='';try{await request('/api/checkins','POST',{plan_id:checking.value.id,duration_minutes:n,note:checkForm.value.note});modal.value='';await load();uni.showToast({title:t('success'),icon:'none'});}catch(e:any){formError.value=e.message;}finally{busy.value=false;}}
async function archivePlan(){busy.value=true;try{await request('/api/plans/'+archiveTarget.value.id,'DELETE');archiveTarget.value=null;await load();}catch(e){showError(e);}finally{busy.value=false;}}
async function readArticle(id:string){try{article.value=await request('/api/articles/'+id+'?locale='+locale.value);}catch(e){showError(e);}}
async function saveProfile(){const n=Number(profileForm.value.weekly_goal);if(!profileForm.value.nickname.trim()||!Number.isInteger(n)||n<1||n>7){error.value='required';return;}busy.value=true;try{me.value=await request('/api/me','PATCH',{nickname:profileForm.value.nickname.trim(),weekly_goal:n,locale:locale.value});error.value='';uni.showToast({title:t('success'),icon:'none'});}catch(e){showError(e);}finally{busy.value=false;}}
// #ifdef H5
function keyboardActivate(e:KeyboardEvent){const target=e.target as HTMLElement;if((e.key==='Enter'||e.key===' ')&&target.getAttribute('role')==='button'&&target.getAttribute('aria-disabled')!=='true'){e.preventDefault();target.click();}}
onMounted(()=>document.addEventListener('keydown',keyboardActivate));
onUnmounted(()=>document.removeEventListener('keydown',keyboardActivate));
// #endif
onMounted(()=>{setLocale(locale.value);if(sessionReady.value)void load();});
</script>
<style src="../../styles/main.css"></style>
<style src="../../styles/movements.css"></style>
